# 构建并测试
name: Build And Test

# 设置触发器
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 使用clang进行构建
  clang-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-11]

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v2

    - name: build on clang
      run: python3 ./build.py debug test
    
   
  # 在gcc下构建
  gcc-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-11]

    env:
      CC: gcc-10
      CXX: g++-10

    steps:
    - uses: actions/checkout@v2

    - name: build on gcc
      run: python3 ./build.py debug test


  # 使用msvc构建
  msvc-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: build on msvc
      # 设置msvc环境
      run: pwsh ./setup_msvc.ps1 debug test
